const KEY="financeTrackerV6",SETTINGS="financeTrackerV6Settings";
const EXPENSE=["Housing","Bills","Groceries","Transport","Eating out","Shopping","Entertainment","Gym","Health","Debt","Savings / investing","Education","Family","Travel","Other"];
const INCOME=["Salary","Bonus","Freelance","Benefits","Refund","Interest","Gift","Other income"];
const MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const CURRENCIES=["KES","GBP","USD","EUR"];
let data=read(KEY,{accounts:[],transactions:[],budgets:[],debts:[]});
// Goals were removed from the app to keep the tracker simple. Ignore any legacy goal data.
if (data.goals) { delete data.goals; save(); }
let settings=read(SETTINGS,{baseCurrency:"KES",rates:{KES:1,GBP:175.93,USD:129.5,EUR:150.2}});
let view="dashboard",selected=new Date(new Date().getFullYear(),new Date().getMonth(),1);

function read(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function saveSettings(){localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(v,c){return new Intl.NumberFormat("en-GB",{style:"currency",currency:c,minimumFractionDigits:2}).format(Number(v)||0)}
function convert(v,from,to){if(from===to)return +v||0;const kes=(+v||0)*(settings.rates[from]||1);return kes/(settings.rates[to]||1)}
function acc(i){return data.accounts.find(a=>a.id===i)}
function icon(a){if(!a)return"•";return a.type==="mpesa"?"📱":a.type==="savings"?"🎯":a.type==="cash"?"💵":a.type==="credit"?"💳":a.type==="debt"?"📉":a.currency==="KES"?"🇰🇪":"💳"}
function typeName(a){return {bank:"Bank account",savings:"Savings account",mpesa:"M-PESA",cash:"Cash",credit:"Credit card",debt:"Loan / debt",other:"Other"}[a?.type]||"Other"}
function iso(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function dObj(s){return new Date(s+"T12:00:00")}
function dateText(s){return dObj(s).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function monthTx(y=selected.getFullYear(),m=selected.getMonth()){return data.transactions.filter(t=>{const d=dObj(t.date);return d.getFullYear()===y&&d.getMonth()===m})}
function completed(ts){return ts.filter(t=>t.status==="completed")}
function stats(ts){return{income:ts.filter(t=>t.type==="income").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),spending:ts.filter(t=>t.type==="expense").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0)}}
function balances(){const b={};data.accounts.forEach(a=>b[a.id]=+a.openingBalance||0);data.transactions.forEach(t=>{if(t.status!=="completed")return;if(t.type==="transfer"){if(t.fromAccountId)b[t.fromAccountId]=(b[t.fromAccountId]||0)-+t.amount-(+t.transferFee||0);if(t.toAccountId)b[t.toAccountId]=(b[t.toAccountId]||0)+ +t.amount}else if(t.type==="income")b[t.accountId]=(b[t.accountId]||0)+ +t.amount;else if(t.type==="expense")b[t.accountId]=(b[t.accountId]||0)- +t.amount});return b}
function netWorth(){const b=balances();return data.accounts.reduce((s,a)=>s+convert(b[a.id]||0,a.currency,settings.baseCurrency),0)}
function historicalAverage(){const v=[];for(let i=1;i<=6;i++){const d=new Date(selected);d.setMonth(d.getMonth()-i);const s=stats(completed(monthTx(d.getFullYear(),d.getMonth())));if(s.spending)v.push(s.spending)}return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function upcoming(){const now=new Date();now.setHours(0,0,0,0);const end=new Date(now);end.setDate(end.getDate()+30);return data.transactions.filter(t=>t.status==="upcoming"&&dObj(t.date)>=now&&dObj(t.date)<=end).sort((a,b)=>a.date.localeCompare(b.date))}
function period(){return `<div class="period"><div class="period-buttons"><button class="active">Month</button><button onclick="setLastMonth()">Last month</button><button onclick="setThisYear()">This year</button></div><div class="period-current"><button onclick="moveMonth(-1)">‹</button><span>${MONTHS[selected.getMonth()]} ${selected.getFullYear()}</span><button onclick="moveMonth(1)">›</button></div></div>`}
function moveMonth(n){selected.setMonth(selected.getMonth()+n);render()}
function setLastMonth(){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);selected=d;render()}
function setThisYear(){selected=new Date(new Date().getFullYear(),0,1);render()}
function kpi(a,b,c,cl=""){return `<div class="card kpi"><div class="kpi-label">${a}</div><div class="kpi-value ${cl}">${b}</div><div class="kpi-sub">${c}</div></div>`}
function header(t,s){document.getElementById("pageTitle").textContent=t;document.getElementById("pageSubtitle").textContent=s}
function nav(){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===view))}
function render(){nav();document.getElementById("baseCurrency").value=settings.baseCurrency;({dashboard:dashboard,bank:accountView,mpesa:accountView,savings:accountView,transactions:transactions,upcoming:upcomingPage,budgets:budgets,analytics:analytics,networth:networthPage,import:importPage,converter:converterPage,settings:settingsPage}[view]||dashboard)()}
document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>{view=n.dataset.view;render()}));
document.addEventListener("DOMContentLoaded",render);

function dashboard(){
 header("Dashboard","Your complete financial picture");const s=stats(completed(monthTx())),avg=historicalAverage(),diff=avg==null?null:s.spending-avg,u=upcoming();
 document.getElementById("content").innerHTML=`${period()}<div class="hero-grid"><div class="card wealth"><div class="eyebrow">TOTAL NET WORTH</div><div class="wealth-number">${money(netWorth(),settings.baseCurrency)}</div><div class="wealth-secondary">Across ${data.accounts.length} account${data.accounts.length===1?"":"s"}</div><span class="pill">${data.transactions.length} transactions tracked</span></div><div class="card"><div class="section-head"><div><div class="eyebrow">UPCOMING</div><h2>Next 30 days</h2></div><span class="muted">${u.length}</span></div>${upHTML(u.slice(0,5))}</div></div>
 <div class="grid four">${kpi("Income",money(s.income,settings.baseCurrency),"Completed this month","positive")}${kpi("Actual spending",money(s.spending,settings.baseCurrency),"Transfers excluded","negative")}${kpi("Net cash flow",money(s.income-s.spending,settings.baseCurrency),"Income minus spending",s.income>=s.spending?"positive":"negative")}${kpi("Savings rate",(s.income?s.income-s.spending:0?(s.income-s.spending)/s.income*100:0).toFixed(1)+"%","Net cash flow / income",(s.income-s.spending)>=0?"positive":"negative")}</div>
 <div class="card" style="margin-top:13px">${accountsHTML()}</div><div class="grid two-cols" style="margin-top:13px">${categoriesHTML()}${cashChart()}</div>
 <div class="grid four" style="margin-top:13px">${kpi("Vs average",diff==null?"—":(diff>0?"+":"−")+money(Math.abs(diff),settings.baseCurrency),diff==null?"Add previous months":`${Math.abs(diff/avg*100).toFixed(1)}% ${diff>0?"above":"below"} average`,diff>0?"negative":"positive")}${kpi("Upcoming income",money(u.filter(t=>t.type==="income").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),settings.baseCurrency),"Next 30 days","positive")}${kpi("Upcoming spending",money(u.filter(t=>t.type==="expense").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),settings.baseCurrency),"Next 30 days","negative")}${kpi("Accounts",data.accounts.length,"Bank, M-PESA & savings","")}</div>`
}
function accountsHTML(){
 const b=balances();if(!data.accounts.length)return `<div class="empty">No accounts yet. <button class="secondary" onclick="openAccount()">Add your first account</button></div>`;
 const total=Math.max(netWorth(),1);return `<div class="section-head"><div><div class="eyebrow">ACCOUNTS</div><h2>Where your money is</h2></div><button class="secondary" onclick="openAccount()">+ Add account</button></div><div style="overflow:auto"><table class="accounts-table"><thead><tr><th>Account</th><th>Type</th><th>Balance</th><th>Share</th></tr></thead><tbody>${data.accounts.map(a=>{const v=convert(b[a.id]||0,a.currency,settings.baseCurrency),share=Math.max(0,v)/total*100;return `<tr><td><span class="account-name">${icon(a)} ${esc(a.name)}</span><div class="account-type">${a.currency}</div></td><td>${typeName(a)}</td><td class="account-balance">${money(b[a.id]||0,a.currency)}<div class="account-type">≈ ${money(v,settings.baseCurrency)}</div></td><td><div class="progress"><div style="width:${Math.min(100,share)}%"></div></div></td></tr>`}).join("")}</tbody></table></div>`
}
function categoriesHTML(){
 const o={};completed(monthTx()).filter(t=>t.type==="expense").forEach(t=>o[t.category]=(o[t.category]||0)+convert(t.amount,t.currency,settings.baseCurrency));const e=Object.entries(o).sort((a,b)=>b[1]-a[1]),tot=e.reduce((s,x)=>s+x[1],0);return `<div class="card"><div class="section-head"><div><div class="eyebrow">SPENDING</div><h2>By category</h2></div><span class="muted">${money(tot,settings.baseCurrency)}</span></div>${e.length?e.slice(0,10).map(x=>`<div class="category"><div class="cat-top"><span>${esc(x[0])}</span><span>${money(x[1],settings.baseCurrency)}</span></div><div class="bar"><div style="width:${tot?x[1]/tot*100:0}%"></div></div></div>`).join(""):`<div class="empty">No spending this month.</div>`}</div>`
}
function cashChart(){
 let vals=[];for(let i=5;i>=0;i--){const d=new Date(selected);d.setMonth(d.getMonth()-i);const s=stats(completed(monthTx(d.getFullYear(),d.getMonth())));vals.push({l:MONTHS[d.getMonth()],v:s.income})}const max=Math.max(1,...vals.map(x=>x.v));return `<div class="card"><div class="section-head"><div><div class="eyebrow">INCOME TREND</div><h2>Last 6 months</h2></div></div><div class="chart">${vals.map(x=>`<div class="chart-col"><div class="chart-value">${money(x.v,settings.baseCurrency)}</div><div class="chart-bar" style="height:${Math.max(2,x.v/max*130)}px"></div><div class="chart-label">${x.l}</div></div>`).join("")}</div></div>`
}
function upHTML(list){if(!list.length)return `<div class="empty">Nothing upcoming.</div>`;return `<div class="upcoming">${list.map(t=>{const d=dObj(t.date),from=t.type==="transfer"?acc(t.fromAccountId):acc(t.accountId),to=t.type==="transfer"?acc(t.toAccountId):null;return `<div class="up-item"><div class="date-box"><strong>${d.getDate()}</strong><span>${MONTHS[d.getMonth()]}</span></div><div><div class="item-title">${esc(t.description)}</div><div class="item-meta">${esc(from?.name||"Unknown")}${to?" → "+esc(to.name):" · "+esc(t.category)}</div></div><div class="${t.type==="income"?"amount-income":t.type==="expense"?"amount-expense":""}">${t.type==="income"?"+":t.type==="expense"?"−":"↔"}${money(t.amount,t.currency)}</div></div>`}).join("")}</div>`}

function accountView(){
 const type=view,as=data.accounts.filter(a=>a.type===type),b=balances();header(type==="mpesa"?"M-PESA":type==="savings"?"Savings":"Bank",`${type==="mpesa"?"M-PESA wallet":type==="savings"?"Savings accounts":"Bank accounts"} dashboard`);
 if(!as.length){document.getElementById("content").innerHTML=`<div class="card empty">No ${type==="mpesa"?"M-PESA":type==="savings"?"savings":"bank"} accounts yet.<br><br><button class="primary" onclick="openAccount()">+ Add account</button></div>`;return}
 const ids=new Set(as.map(a=>a.id)),ts=data.transactions.filter(t=>t.type==="transfer"?ids.has(t.fromAccountId)||ids.has(t.toAccountId):ids.has(t.accountId)),s=stats(completed(ts)),total=as.reduce((z,a)=>z+convert(b[a.id]||0,a.currency,settings.baseCurrency),0);
 document.getElementById("content").innerHTML=`${period()}<div class="card wealth" style="margin-bottom:13px"><div class="eyebrow">${type.toUpperCase()}</div><div class="wealth-number">${money(total,settings.baseCurrency)}</div><div class="wealth-secondary">${as.length} account${as.length===1?"":"s"}</div></div><div class="grid four">${kpi("Money in",money(s.income,settings.baseCurrency),"Income only","positive")}${kpi("Actual spending",money(s.spending,settings.baseCurrency),"Transfers excluded","negative")}${kpi("Net movement",money(s.income-s.spending,settings.baseCurrency),"Income minus spending",(s.income-s.spending)>=0?"positive":"negative")}${kpi("Accounts",as.length,"Within this dashboard","")}</div><div class="card" style="margin-top:13px">${accountsHTMLFiltered(as,b)}</div><div class="grid two-cols" style="margin-top:13px"><div class="card"><div class="section-head"><h2>Recent activity</h2></div>${txTable(ts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12))}</div><div class="card"><div class="section-head"><h2>Upcoming</h2></div>${upHTML(upcoming().filter(t=>t.type==="transfer"?ids.has(t.fromAccountId)||ids.has(t.toAccountId):ids.has(t.accountId)).slice(0,8))}</div></div>`
}
function accountsHTMLFiltered(as,b){return `<div class="section-head"><div><div class="eyebrow">ACCOUNTS</div><h2>Balances</h2></div><button class="secondary" onclick="openAccount()">+ Add account</button></div><div style="overflow:auto"><table class="accounts-table"><thead><tr><th>Account</th><th>Currency</th><th>Balance</th><th></th></tr></thead><tbody>${as.map(a=>`<tr><td><span class="account-name">${icon(a)} ${esc(a.name)}</span><div class="account-type">${typeName(a)}</div></td><td>${a.currency}</td><td class="account-balance">${money(b[a.id]||0,a.currency)}<div class="account-type">≈ ${money(convert(b[a.id]||0,a.currency,settings.baseCurrency),settings.baseCurrency)}</div></td><td><button class="delete" onclick="deleteAccount('${a.id}')">×</button></td></tr>`).join("")}</tbody></table></div>`}
function txTable(list){if(!list.length)return `<div class="empty">No transactions.</div>`;return `<div style="overflow:auto"><table class="tx-table"><thead><tr><th>Date</th><th>Description</th><th>From / Account</th><th>To</th><th>Category</th><th>Type</th><th>Status</th><th>Amount</th><th></th></tr></thead><tbody>${list.map(t=>{const from=t.type==="transfer"?acc(t.fromAccountId):acc(t.accountId),to=t.type==="transfer"?acc(t.toAccountId):null;return `<tr><td>${dateText(t.date)}</td><td><strong>${esc(t.description)}</strong>${t.recurring?'<div class="item-meta">Recurring</div>':""}</td><td>${icon(from)} ${esc(from?.name||"Unknown")}</td><td>${to?icon(to)+" "+esc(to.name):"—"}</td><td>${esc(t.category)}</td><td class="${t.type==="income"?"amount-income":t.type==="expense"?"amount-expense":""}">${t.type==="income"?"Income":t.type==="expense"?"Outgoing":"Transfer"}</td><td><span class="badge ${t.status}">${t.status}</span></td><td class="${t.type==="income"?"amount-income":t.type==="expense"?"amount-expense":""}">${t.type==="income"?"+":t.type==="expense"?"−":""}${money(t.amount,t.currency)}</td><td><button class="delete" onclick="deleteTransaction('${t.id}')">×</button></td></tr>`}).join("")}</tbody></table></div>`}
function transactions(){header("Transactions","Every income, expense and transfer");document.getElementById("content").innerHTML=`<div class="card"><div class="section-head"><div><div class="eyebrow">ALL ACTIVITY</div><h2>Transaction ledger</h2></div><button class="primary" onclick="openTransaction()">+ Transaction</button></div><div class="toolbar" style="margin-bottom:14px"><input id="txSearch" placeholder="Search..." oninput="filterTx()"><select id="txFilter" onchange="filterTx()"><option value="">All types</option><option value="income">Income</option><option value="expense">Outgoing</option><option value="transfer">Transfers</option></select><select id="txAccountFilter" onchange="filterTx()"><option value="">All accounts</option>${data.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")}</select></div><div id="txResults">${txTable(data.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)))}</div></div>`}
function filterTx(){const q=(document.getElementById("txSearch").value||"").toLowerCase(),ty=document.getElementById("txFilter").value,ai=document.getElementById("txAccountFilter").value;const l=data.transactions.filter(t=>{const text=[t.description,t.category,acc(t.accountId)?.name,acc(t.fromAccountId)?.name,acc(t.toAccountId)?.name].join(" ").toLowerCase(),matchAcc=!ai||(t.accountId===ai||t.fromAccountId===ai||t.toAccountId===ai);return(!q||text.includes(q))&&(!ty||t.type===ty)&&matchAcc}).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById("txResults").innerHTML=txTable(l)}
function upcomingPage(){header("Upcoming","Expected income, spending and transfers");const u=data.transactions.filter(t=>t.status==="upcoming").sort((a,b)=>a.date.localeCompare(b.date));document.getElementById("content").innerHTML=`<div class="grid four">${kpi("Upcoming income",money(u.filter(t=>t.type==="income").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),settings.baseCurrency),"All future planned income","positive")}${kpi("Upcoming spending",money(u.filter(t=>t.type==="expense").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),settings.baseCurrency),"All future planned spending","negative")}${kpi("Upcoming transfers",money(u.filter(t=>t.type==="transfer").reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),settings.baseCurrency),"Own-account movement","")}${kpi("Transactions",u.length,"Planned items","")}</div><div class="card" style="margin-top:13px">${txTable(u)}</div>`}
function budgets(){header("Budgets","Set limits and see where you are over budget");const m=completed(monthTx()),sp=stats(m).spending;document.getElementById("content").innerHTML=`<div class="card"><div class="section-head"><div><div class="eyebrow">MONTHLY BUDGETS</div><h2>${MONTHS[selected.getMonth()]} ${selected.getFullYear()}</h2></div><button class="primary" onclick="addBudget()">+ Budget</button></div>${data.budgets.length?data.budgets.map(b=>{const actual=m.filter(t=>t.type==="expense"&&t.category===b.category).reduce((s,t)=>s+convert(t.amount,t.currency,settings.baseCurrency),0),p=b.amount?actual/b.amount*100:0;return `<div class="category"><div class="cat-top"><span>${esc(b.category)}</span><span>${money(actual,settings.baseCurrency)} / ${money(b.amount,settings.baseCurrency)} ${p>100?"🔴":p>=80?"🟠":"🟢"}</span></div><div class="bar"><div style="width:${Math.min(100,p)}%;background:${p>100?"var(--red)":p>=80?"var(--orange)":"var(--green)"}"></div></div><div class="item-meta">${p.toFixed(0)}% used</div></div>`}).join(""):`<div class="empty">No budgets yet. Add one for groceries, gym, transport, eating out, etc.</div>`}</div>`}
function addBudget(){const c=prompt("Category for the monthly budget:", "Groceries");if(!c)return;const a=Number(prompt("Budget amount in "+settings.baseCurrency+":","20000"));if(!a||a<=0)return;data.budgets.push({id:id(),category:c,amount:a,currency:settings.baseCurrency});save();render()}
function analytics(){header("Analytics","Understand your spending and financial behaviour");const s=stats(completed(monthTx())),avg=historicalAverage(),cats={};completed(monthTx()).filter(t=>t.type==="expense").forEach(t=>cats[t.category]=(cats[t.category]||0)+convert(t.amount,t.currency,settings.baseCurrency));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];document.getElementById("content").innerHTML=`${period()}<div class="grid four">${kpi("Spending",money(s.spending,settings.baseCurrency),"This month","negative")}${kpi("Income",money(s.income,settings.baseCurrency),"This month","positive")}${kpi("Savings rate",(s.income?(s.income-s.spending)/s.income*100:0).toFixed(1)+"%","Income saved","")}${kpi("6-month average",avg==null?"—":money(avg,settings.baseCurrency),"Monthly spending","")}</div><div class="grid two-cols" style="margin-top:13px"><div class="card"><div class="eyebrow">BIGGEST CATEGORY</div><div class="big-stat">${top?esc(top[0]):"—"}</div><div class="muted">${top?money(top[1],settings.baseCurrency):"No spending recorded"}</div></div><div class="card"><div class="eyebrow">FINANCIAL HEALTH</div><div class="big-stat">${healthScore(s)} / 100</div><div class="muted">Simple budgeting and cash-flow indicator, not financial advice.</div></div></div><div class="card" style="margin-top:13px">${categoriesHTML()}</div>`}
function healthScore(s){if(!s.income)return 0;const saving=Math.max(0,Math.min(100,s.income?s.net/s.income*100:0));const avg=historicalAverage();const spendScore=avg==null?70:Math.max(0,Math.min(100,100-(s.spending/Math.max(avg,1)-1)*100));return Math.round(saving*.6+spendScore*.4)}
function networthPage(){header("Net worth","See how your overall financial position changes");const b=balances(),rows=data.accounts.map(a=>({a,v:convert(b[a.id]||0,a.currency,settings.baseCurrency)}));document.getElementById("content").innerHTML=`<div class="card wealth"><div class="eyebrow">CURRENT NET WORTH</div><div class="wealth-number">${money(netWorth(),settings.baseCurrency)}</div><div class="wealth-secondary">Assets less tracked liabilities</div></div><div class="card" style="margin-top:13px">${accountsHTML()}</div><div class="card" style="margin-top:13px"><div class="section-head"><h2>Account contribution</h2></div>${rows.map(x=>`<div class="metric"><span>${icon(x.a)} ${esc(x.a.name)}</span><strong>${money(x.v,settings.baseCurrency)}</strong></div>`).join("")}</div>`}
function importPage(){header("Import / Export","Back up your data or import bank CSV files");document.getElementById("content").innerHTML=`<div class="grid two-cols"><div class="card"><div class="eyebrow">BACKUP</div><h2>Export complete backup</h2><p class="muted">Creates a JSON file containing accounts, transactions and budgets.</p><button class="primary" onclick="exportData()">Export backup</button><div style="margin-top:20px"><label style="font-size:11px;font-weight:750">Restore backup<input type="file" id="restoreFile" accept=".json" onchange="restoreBackup(event)"></label></div></div><div class="card"><div class="eyebrow">BANK CSV</div><h2>Import transactions</h2><p class="muted">Upload a CSV with columns for date, description and amount. The importer will create transactions against your selected account.</p><select id="csvAccount" style="padding:9px;border:1px solid var(--line);border-radius:8px;width:100%;margin:10px 0">${data.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")}</select><input type="file" id="csvFile" accept=".csv"><button class="primary" style="margin-top:10px" onclick="importCSV()">Import CSV</button><div class="note" style="margin-top:12px">CSV import is intentionally simple: review imported rows afterwards. Amounts above zero are treated as income and amounts below zero as expenses.</div></div></div>`}
function exportData(){const blob=new Blob([JSON.stringify({version:6,exportedAt:new Date().toISOString(),data,settings},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="finance-tracker-backup.json";a.click();URL.revokeObjectURL(u)}
function restoreBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.data||!Array.isArray(x.data.accounts)||!Array.isArray(x.data.transactions))throw 0;if(confirm("Replace current data with this backup?")){data=x.data;settings=x.settings||settings;save();saveSettings();render()}}catch{alert("That backup file is not valid.")}};r.readAsText(f)}
function importCSV(){const f=document.getElementById("csvFile").files[0],ai=document.getElementById("csvAccount").value;if(!f||!ai)return alert("Choose a CSV file and account.");const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);if(lines.length<2)return alert("CSV has no rows.");const headers=lines[0].split(",").map(x=>x.trim().toLowerCase());const di=headers.findIndex(x=>x.includes("date")),si=headers.findIndex(x=>x.includes("description")||x.includes("details")||x.includes("merchant")),ai2=headers.findIndex(x=>x==="amount"||x.includes("amount"));if(di<0||si<0||ai2<0)return alert("CSV needs date, description and amount columns.");let count=0;lines.slice(1).forEach(line=>{const c=line.split(",");const date=c[di]?.trim(),desc=c[si]?.trim(),amount=Number((c[ai2]||"").replace(/[£$€,]/g,""));if(date&&desc&&!isNaN(amount)){data.transactions.push({id:id(),description:desc,amount:Math.abs(amount),currency:acc(ai).currency,type:amount>=0?"income":"expense",accountId:ai,category:amount>=0?"Other income":"Other",date:normalizeCSVDate(date),status:"completed",recurring:false});count++}});save();alert(`${count} transaction${count===1?"":"s"} imported. Review them in Transactions.`);view="transactions";render()};r.readAsText(f)}
function normalizeCSVDate(s){if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return isNaN(d)?iso():iso(d)}
function converterPage(){header("Currency Converter","Convert between GBP, KES, USD and EUR");document.getElementById("content").innerHTML=`<div class="card" style="max-width:550px"><div class="eyebrow">CURRENCY</div><h2>Conversion</h2><div class="two" style="margin-top:18px"><label>Amount<input id="cvAmount" type="number" value="1" oninput="convertPage()"></label><label>From<select id="cvFrom" onchange="convertPage()">${CURRENCIES.map(c=>`<option>${c}</option>`).join("")}</select></label></div><label>To<select id="cvTo" onchange="convertPage()">${CURRENCIES.map(c=>`<option ${c===settings.baseCurrency?"selected":""}>${c}</option>`).join("")}</select></label><div class="conversion-result" id="cvResult" style="font-size:30px;font-weight:900;text-align:center;background:#f7f8fa;padding:20px;border-radius:10px;margin-top:10px">—</div><label>Rates to KES (update manually)<div class="two">${CURRENCIES.filter(c=>c!=="KES").map(c=>`<label>${c}<input type="number" step=".0001" value="${settings.rates[c]}" onchange="settings.rates.${c}=+this.value||settings.rates.${c};saveSettings();convertPage()"></label>`).join("")}</div></label></div>`;convertPage()}
function convertPage(){const a=+document.getElementById("cvAmount").value||0,f=document.getElementById("cvFrom").value,t=document.getElementById("cvTo").value;document.getElementById("cvResult").textContent=money(a,f)+" = "+money(convert(a,f,t),t)}
function settingsPage(){header("Settings","Manage preferences and local data");document.getElementById("content").innerHTML=`<div class="card"><div class="eyebrow">PREFERENCES</div><h2>Settings</h2><div class="setting"><span>Dashboard currency</span><select onchange="settings.baseCurrency=this.value;saveSettings();render()"><option ${settings.baseCurrency==="KES"?"selected":""}>KES</option><option ${settings.baseCurrency==="GBP"?"selected":""}>GBP</option><option ${settings.baseCurrency==="USD"?"selected":""}>USD</option><option ${settings.baseCurrency==="EUR"?"selected":""}>EUR</option></select></div><div class="setting"><span>Accounts</span><strong>${data.accounts.length}</strong></div><div class="setting"><span>Transactions</span><strong>${data.transactions.length}</strong></div><div class="setting"><span>Storage</span><strong>Browser only</strong></div><div class="setting"><span>Reset all local data</span><button class="secondary danger" onclick="resetAll()">Reset tracker</button></div><div class="note">Your financial data stays in this browser. GitHub Pages hosts the application files; it does not receive these transactions.</div></div>`}
function openTransaction(){if(!data.accounts.length){alert("Add an account first.");openAccount();return}populateAccounts();document.getElementById("txDesc").value="";document.getElementById("txAmount").value="";document.getElementById("txType").value="expense";document.getElementById("txDate").value=iso();document.getElementById("transferDate").value=iso();document.getElementById("txStatus").value="completed";document.getElementById("transferStatus").value="completed";document.getElementById("txRecurring").checked=false;document.getElementById("txRepeatUntil").value="";document.getElementById("transferFee").value=0;updateTxForm();document.getElementById("transactionModal").classList.add("show")}
function populateAccounts(){const opts=data.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} (${a.currency})</option>`).join("");document.getElementById("txAccount").innerHTML=opts;document.getElementById("txFrom").innerHTML=opts;document.getElementById("txTo").innerHTML=opts;if(data.accounts.length>1){document.getElementById("txFrom").value=data.accounts[0].id;document.getElementById("txTo").value=data.accounts[1].id}syncTransfer()}
function syncTransfer(){const f=acc(document.getElementById("txFrom").value),t=acc(document.getElementById("txTo").value);document.getElementById("txCurrency").value=f?.currency||"KES";document.getElementById("transferSummary").textContent=f&&t?`${icon(f)} ${f.name} → ${icon(t)} ${t.name} · ${f.currency===t.currency?f.currency:"Different currencies"}`:"Choose two accounts."}
function updateTxForm(){const tr=document.getElementById("txType").value==="transfer";document.getElementById("normalTx").classList.toggle("hidden",tr);document.getElementById("transferTx").classList.toggle("hidden",!tr);if(tr)syncTransfer();const type=document.getElementById("txType").value;document.getElementById("txCategory").innerHTML=(type==="income"?INCOME:EXPENSE).map(x=>`<option>${esc(x)}</option>`).join("")}
document.addEventListener("change",e=>{if(e.target.id==="txRecurring")document.getElementById("recurringFields").classList.toggle("hidden",!e.target.checked)})
function saveTransaction(){
 const type=document.getElementById("txType").value,desc=document.getElementById("txDesc").value.trim(),amount=+document.getElementById("txAmount").value;if(!desc||!amount||amount<=0)return alert("Enter a description and a valid positive amount.");
 if(type==="transfer"){const from=document.getElementById("txFrom").value,to=document.getElementById("txTo").value,fa=acc(from),ta=acc(to);if(!fa||!ta||from===to)return alert("Choose two different accounts.");if(fa.currency!==ta.currency)return alert("Transfers currently require the same currency. This prevents an accidental exchange rate.");data.transactions.push({id:id(),description:desc,amount,currency:fa.currency,type,date:document.getElementById("transferDate").value,status:document.getElementById("transferStatus").value,category:"Transfer",fromAccountId:from,toAccountId:to,transferFee:+document.getElementById("transferFee").value||0,recurring:false});selected=new Date(document.getElementById("transferDate").value+"T12:00:00")}
 else{const date=document.getElementById("txDate").value,tx={id:id(),description:desc,amount,currency:document.getElementById("txCurrency").value,type,accountId:document.getElementById("txAccount").value,category:document.getElementById("txCategory").value,date,status:document.getElementById("txStatus").value,recurring:document.getElementById("txRecurring").checked,frequency:document.getElementById("txFrequency").value,repeatUntil:document.getElementById("txRepeatUntil").value||null};data.transactions.push(tx);if(tx.recurring)generateRecurring(tx);selected=new Date(date+"T12:00:00")}
 selected.setDate(1);save();closeModal("transactionModal");render()}
function generateRecurring(base){const until=base.repeatUntil;if(!until)return;let d=dObj(base.date);const add={weekly:()=>d.setDate(d.getDate()+7),monthly:()=>d.setMonth(d.getMonth()+1),quarterly:()=>d.setMonth(d.getMonth()+3),yearly:()=>d.setFullYear(d.getFullYear()+1)}[base.frequency];let guard=0;while(guard++<500){add();const ds=iso(d);if(ds>until)break;data.transactions.push({...base,id:id(),date:ds,status:"upcoming",recurring:true})}}
function openAccount(){document.getElementById("accName").value="";document.getElementById("accType").value="bank";document.getElementById("accCurrency").value=settings.baseCurrency;document.getElementById("accOpening").value=0;document.getElementById("accountModal").classList.add("show")}
function saveAccount(){const name=document.getElementById("accName").value.trim(),opening=+document.getElementById("accOpening").value||0;if(!name)return alert("Enter an account name.");data.accounts.push({id:id(),name,type:document.getElementById("accType").value,currency:document.getElementById("accCurrency").value,openingBalance:opening});save();closeModal("accountModal");render()}
function deleteAccount(i){if(data.transactions.some(t=>t.accountId===i||t.fromAccountId===i||t.toAccountId===i))return alert("This account has transactions. Delete those first.");if(confirm("Delete this account?")){data.accounts=data.accounts.filter(a=>a.id!==i);save();render()}}
function deleteTransaction(i){if(confirm("Delete this transaction?")){data.transactions=data.transactions.filter(t=>t.id!==i);save();render()}}
function closeModal(i){document.getElementById(i).classList.remove("show")}
function resetAll(){if(confirm("Delete all accounts, transactions and budgets from this browser?")){localStorage.removeItem(KEY);location.reload()}}
window.addEventListener("click",e=>{if(e.target.classList.contains("modal"))e.target.classList.remove("show")});
